lib-cpp:build:linux_gcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: build
  script:
    - cd lib-cpp
    - set -eo pipefail
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ ..
    - make
  artifacts:
    paths:
      - lib-cpp/build

lib-cpp:build:wasm_emcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: build
  script:
    - cd lib-cpp
    - set -eo pipefail
    - mkdir build-wasm && cd build-wasm
    - emcmake cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
  artifacts:
    paths:
      - lib-cpp/build-wasm

lib-cpp:test:linux_gcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: test
  script:
    - cd lib-cpp
    - cd build
    - make coverage-base
    - ctest
  dependencies:
    - lib-cpp:build:linux_gcc
  artifacts:
    paths:
      - lib-cpp/build

lib-cpp:test:wasm_emcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: test
  script:
    - cd lib-cpp
    - cd build-wasm
    - ctest -VV
  dependencies:
    - lib-cpp:build:wasm_emcc
  artifacts:
    paths:
      - lib-cpp/build-wasm

lib-cpp:format:
  image: devrosch/cppcicdenv:2021-01-01
  stage: test
  script:
    - cd lib-cpp
    - cd build && make clang-format-check
  dependencies:
    - lib-cpp:build:linux_gcc

lib-cpp:lint:
  image: devrosch/cppcicdenv:2021-01-01
  stage: test
  script:
    - cd lib-cpp
    - cd build && make clang-tidy
  dependencies:
    - lib-cpp:build:linux_gcc

lib-cpp:coverage:linux_gcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: test
  variables:
    COVERAGE_THRESHOLD: "95.0"
  script:
    - cd lib-cpp
    - cd build
    - set -eo pipefail
    - make coverage-capture
    - "make coverage-report
      | tee /dev/stderr
      | grep -E 'lines\\.{6,}:'
      | awk -F': |%' '{print $2}'
      | { read coverage; echo \"=== line coverage: ${coverage}%, threshold: ${COVERAGE_THRESHOLD}% ===\"; (( $(echo \"$coverage >= $COVERAGE_THRESHOLD\" | bc -l) )); }"
  dependencies:
    - lib-cpp:test:linux_gcc
  needs:
    - lib-cpp:test:linux_gcc
  coverage: '/lines\.+: \d+\.\d+%/'
  artifacts:
    paths:
      - lib-cpp/build/coverage

lib-cpp:doc:doxygen:
  image: devrosch/cppcicdenv:2021-01-01
  stage: doc
  script:
    - cd lib-cpp
    - cd build && doxygen ./doxy.config
  dependencies:
    - lib-cpp:build:linux_gcc
  artifacts:
    paths:
      - lib-cpp/build/doc

lib-cpp:release:linux_gcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: release
  script:
    - cd lib-cpp
    - set -eo pipefail
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ ..
    - make
  artifacts:
    paths:
      - lib-cpp/build

lib-cpp:release:wasm_emcc:
  image: devrosch/cppcicdenv:2021-01-01
  stage: release
  script:
    - cd lib-cpp
    - set -eo pipefail
    - mkdir build-wasm && cd build-wasm
    - emcmake cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  artifacts:
    paths:
      - lib-cpp/build-wasm
